### ISSUE TITLE
Configure CI/CD Github Actions

### ISSUE THREAD

**Issue by vmaaik** [vmaaik/endomondo-core-data-and-stats#2]
This is to create a CI/CD pipeline using Github Actions. 

**TODO:**
- [X] run a build 'on push' to feature branch
- [X] run a build 'on push' to develop (once feature gets merged)
- [X] auto-deployment to Heroku when pushed to develop (wait for CI to pass before deploy)
- [X] create a hook on develop and master to prevent committing directly

**Comment by vmaaik** [comment]
It's ready to review.
